name: Deploy Controller Function to Azure -- old
on:
  push:
    paths:
      - github-runner-controller-function/**

  workflow_dispatch:

permissions:
  id-token: write 
  contents: read 

defaults:
  run:
    shell: bash
    working-directory: github-runner-controller-function

env:
  AZURE_FUNCTIONAPP_NAME: 'awesomeproj-dev-controller-function-app'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
        working-directory: github-runner-controller-function

    steps:
    - name: 'Checkout Controller Function'
      uses: actions/checkout@v4
      with: 
        sparse-checkout:
          github-runner-controller-function

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
            python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Login via Azure CLI'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


  
    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
  
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
