name: GHA Self-hosted Infra - Azure 

on:
  push:
    paths:
    - terraform_modules/gh-self-hosted-runner-infra/azure/**

env:
  AZURE_FUNCTIONAPP_NAME: ''   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './github-runner-receiver-function'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout Azure Infra'
      uses: actions/checkout@v4
      with: 
        sparse-checkout:
          terraform_modules/gh-self-hosted-runner-infra/azure